from typing import Optional


class Error(Exception):
    """
    Base exception class for RFC 9457 Problem Details.

    Attributes:
      type (str): A URI reference that identifies the problem type.
      title (str): A short, human-readable summary of the problem type.
      status (int): The HTTP status code generated by the origin server for this occurrence of the problem.
      detail (Optional[str]): A human-readable explanation specific to this occurrence of the problem.
      instance (Optional[str]): A URI reference that identifies the specific occurrence of the problem.

    Args:
      type (str): The problem type URI.
      title (str): The problem summary.
      status (int): The HTTP status code.
      detail (Optional[str], optional): Detailed explanation of the problem. Defaults to None.
      instance (Optional[str], optional): URI identifying the specific occurrence. Defaults to None.
    """

    def __init__(
        self,
        type: str,
        title: str,
        status: int,
        detail: Optional[str] = None,
        instance: Optional[str] = None,
    ):
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
        super().__init__(title)


class InvalidCredentialsError(Error):
    """
    Exception raised when authentication fails due to invalid username or password.

    This error indicates that the credentials provided by the user are incorrect.
    It sets the HTTP status code to 401 Unauthorized and provides a detailed message.
    """

    def __init__(self):
        super().__init__(
            type="https://example.com/probs/invalid-credentials",
            title="Invalid Credentials",
            status=401,
            detail="The username or password provided is incorrect.",
            instance="/api/sign-in",
        )


class UnauthorizedError(Error):
    """
    Exception raised when a user attempts to access a resource without proper authentication.

    This error indicates that the user is not authenticated and sets the HTTP status code to 401 Unauthorized.

    Args:
      instance (Optional[str], optional): URI identifying the specific occurrence. Defaults to None.
    """

    def __init__(self, instance: Optional[str] = None):
        super().__init__(
            type="https://example.com/probs/unauthorized",
            title="Unauthorized",
            status=401,
            detail="Authentication is required to access this resource.",
            instance=instance,
        )
