from typing import Optional

from fastapi import status
from fastapi.exception_handlers import RequestValidationError


class Error(Exception):
    """
    Base exception class for RFC 9457 Problem Details.

    Attributes:
      type (str): A URI reference that identifies the problem type.
      title (str): A short, human-readable summary of the problem type.
      status (int): The HTTP status code generated by the origin server for this occurrence of the problem.
      detail (Optional[str]): A human-readable explanation specific to this occurrence of the problem.
      instance (Optional[str]): A URI reference that identifies the specific occurrence of the problem.

    Args:
      type (str): The problem type URI.
      title (str): The problem summary.
      status (int): The HTTP status code.
      detail (Optional[str], optional): Detailed explanation of the problem. Defaults to None.
      instance (Optional[str], optional): URI identifying the specific occurrence. Defaults to None.
    """

    def __init__(
        self,
        type: str,
        title: str,
        status: int,
        detail: Optional[str] = None,
        instance: Optional[str] = None,
    ):
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
        super().__init__(title)

    def model_dump(self):
        result = {
            "type": self.type,
            "title": self.title,
            "status": self.status,
        }
        if self.detail:
            result["details"] = self.detail
        if self.instance:
            result["instance"] = self.instance
        return result


class InvalidCredentialsError(Error):
    """
    Exception raised when authentication fails due to invalid username or password.

    This error indicates that the credentials provided by the user are incorrect.
    It sets the HTTP status code to 401 Unauthorized and provides a detailed message.
    """

    def __init__(self):
        super().__init__(
            type="https://example.com/probs/invalid-credentials",
            title="Invalid Credentials",
            status=status.HTTP_401_UNAUTHORIZED,
            detail="The username or password provided is incorrect.",
            instance="/api/sign-in",
        )


class UnauthorizedError(Error):
    """
    Exception raised when a user attempts to access a resource without proper authentication.

    This error indicates that the user is not authenticated and sets the HTTP status code to 401 Unauthorized.

    Args:
      instance (Optional[str], optional): URI identifying the specific occurrence. Defaults to None.
    """

    def __init__(self, instance: Optional[str] = None):
        super().__init__(
            type="https://example.com/probs/unauthorized",
            title="Unauthorized",
            status=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication is required to access this resource.",
            instance=instance,
        )


class InternalServerError(Error):
    """
    Exception raised for unexpected server errors.

    This error indicates that an internal server error has occurred and sets the HTTP status code to 500 Internal Server Error.

    Args:
      detail (Optional[str], optional): Detailed explanation of the problem. Defaults to None.
      instance (Optional[str], optional): URI identifying the specific occurrence. Defaults to None.
    """

    def __init__(self, detail: Optional[str] = None, instance: Optional[str] = None):
        super().__init__(
            type="https://example.com/probs/internal-server-error",
            title="Internal Server Error",
            status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=detail or "An unexpected error occurred on the server.",
            instance=instance,
        )


class ValidationError(Error):
    """
    Exception raised for validation errors.

    This error indicates that the input data failed validation and sets the HTTP status code to 400 Bad Request.

    Args:
      detail (Optional[str], optional): Detailed explanation of the problem. Defaults to None.
      instance (Optional[str], optional): URI identifying the specific occurrence. Defaults to None.
    """

    def __init__(
        self,
        errors: RequestValidationError,
        detail: Optional[str] = None,
        instance: Optional[str] = None,
    ):
        super().__init__(
            type="https://example.com/probs/validation-error",
            title="Validation Error",
            status=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=detail or "The input data is invalid.",
            instance=instance,
        )
        self.errors = errors or None

    def model_dump(self):
        result = super().model_dump()
        if self.errors:
            result["errors"] = self.errors.errors()
        return result
