name: Deploy to Firebase Functions

on:
  push:
    paths:
      - .github/workflows/firebase-functions.yml
      - "api/**"
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".tool-versions"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Functions
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
          DB_OPTIONS: ${{ vars.DB_OPTIONS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
        run: |
          cd api
          uv export --no-dev -o requirements.txt >/dev/null
          uv venv venv
          source venv/bin/activate
          uv sync --active
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
          mv .env.template .env
          sed -i "s|^GOOGLE_APPLICATION_CREDENTIALS=.*|GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS|" .env
          sed -i "s|^DB__HOST=.*|DB__HOST=$DB_HOST|" .env
          sed -i "s|^DB__PORT=.*|DB__PORT=$DB_PORT|" .env
          sed -i "s|^DB__USER=.*|DB__USER=$DB_USER|" .env
          sed -i "s|^DB__PASSWORD=.*|DB__PASSWORD=$DB_PASSWORD|" .env
          sed -i "s|^DB__DATABASE=.*|DB__DATABASE=$DB_DATABASE|" .env
          sed -i "s|^DB__OPTIONS=.*|DB__OPTIONS=${DB_OPTIONS//&/\\&}|" .env
          sed -i "s|^JWT__SECRET=.*|JWT__SECRET=$JWT_SECRET|" .env
          firebase functions:artifacts:setpolicy --location asia-east1 --project at-bank-490b5 || echo "Warning: Could not set cleanup policy, continuing with deployment"
          firebase deploy --only functions --project at-bank-490b5 --non-interactive --force
          rm $GOOGLE_APPLICATION_CREDENTIALS
          deactivate
